### ISSUE TITLE
Ability to merge a list of items?

### ISSUE THREAD

**Issue by jsivak** [mk-fg/layered-yaml-attrdict-config#6]
I've got a situation where I'd like to do the following:

base.yaml:

``` yaml
fields:
  -
    src_field: foo
    transform: int
    dst_field: foo_dest
  -
    src_field: bar
    transform: int
    dst_field: bar_dest
```

overlay1.yaml:

``` yaml
fields:
  - 
    src_field: moo
    transform: String
    dst_field: moo_dest
```

and would like the resulting dictionary (after being processed by lya) to be:

``` yaml
fields:
  -
    src_field: foo
    transform: int
    dst_field: foo_dest
  -
    src_field: bar
    transform: int
    dst_field: bar_dest
  - 
    src_field: moo
    transform: String
    dst_field: moo_dest
```

Is this possible?
